services:
  broker:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
  jaeger:
    image: 'jaegertracing/all-in-one:1.57'
    ports:
      - '16686:16686' # Jaeger UI
      - '6831:6831/udp' # traces UDP
      - '14268:14268' # traces HTTP
      - '4313:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP

volumes:
  rabbitmq_data:
